#goal
geometry_msgs/Pose2D[] pickup_poses
geometry_msgs/Pose2D[] destinations
string item
---
#result
bool success
string Error
uint8 state
---
#feedback
#1=goToGood 2=waitForGood 3=Move1 4=Move2 5=waitForReceive
uint8 state
geometry_msgs/Pose2D position
